### PR TITLE
Added Panjabi/Punjabi/Gurmukhi support to polyglossia

### PR DESCRIPTION
**Pull request by punjab**
Submitting Panjabi (10th most spoken language) support to polyglossia.

### CODE REVIEW

**Comment by jspitz** [comment]
Thanks, that's great. Could you also add documentation?

**Comment by punjab** [comment]
Hi @jspitz I have added Gurmukhi/Panjabi documentation as well (except Acknowledgments as that is there for the team to act upon). Let me know if I can be of any further help. And thanks for maintaining Polyglossia!

**Comment by jspitz** [comment]
> Hi @jspitz I have added Gurmukhi/Panjabi documentation as well 

Perfect. Thank you so much.

> (except Acknowledgments as that is there for the team to act upon). Let me know if I can be of any further help. 

It will be my pleasure to credit you there. I'll also add documentation for `\panjabinumber`

> And thanks for maintaining Polyglossia!

Thanks for your valuable contribution!

**Comment by jspitz** [comment]
I have a question: The more common English spelling seems to be Punjabi (rather than Panjabi). Since we use English language expressions in polyglossia: Should we use that?

**Comment by jspitz** [comment]
See
https://www.merriam-webster.com/dictionary/Punjabi
https://en.wikipedia.org/wiki/Punjabi_language
https://www.quora.com/What-is-the-more-appropriate-spelling-of-the-Punjabi-language-Punjabi-or-Panjabi

(and I have a patch for that ready, so no need for you to change that yourself)

**Comment by punjab** [comment]
Hi @jspitz - It is a hotly debated topic - the result of random transliteration in 1920's among english writers using Punjabi, Panjabi or even Panjaabi as the name of the language. This is from a paper I published many years ago  

"Panjabi (or Punjabi) is the spoken language of people originating in the areas of Pun- jab. It is spoken by more than 90 million people[21, 27] in some form. According to Shackle(2003)[28], the word Panjabi was referred to as a language for the first time by Grierson[19]. In his 1916 Linguistic Survey of India [19], he coined the term “Panjabi” as the language of eastern side of Panj-Aab, or land of five rivers, and distinguished it from languages spoken in Western parts of Indo-Aryan territory, which he referred to as Lehandi [19]."

https://www.scribd.com/document/455130962/Arvinder-Kang

**Comment by jspitz** [comment]
Thanks for the explanation. So what shall we do? The <u> spelling seems to be preferred in most sources I consulted, but I don't want to open a sensitive language-political can.

**Pull request merged**
