### PR TITLE
rename \str_lower_case:n to \str_lowercase:n

### PR DESCRIPTION
**Pull request by wspr**
tracking changes in expl3

You may not want to do this immediately if you are not comfortable with picking up expl3 changes as soon as they happen (i.e., only merge this in for release if you expect your users to have fully updated versions of expl3 etc.).

### CODE REVIEW

**Comment by jspitz** [comment]
is the respective expl3 version already on CTAN?

**Comment by wspr** [comment]
Good question, I should have clarified this in my pull request sorry. Yes, the “lowercase” form (without _) is in the most recent release to CTAN.

Regards,
Will

**Comment by jspitz** [comment]
OK, thanks. Another question: is the old version (`\str_lower_case:n`) still supported in that version for backwards compatibility?

**Comment by josephwright** [comment]
It will stay around to the end of 2021.

**Comment by jspitz** [comment]
@reutenauer should we postpone this to 1.48

**Comment by reutenauer** [comment]
We can, but I see no strong reason to.

**Comment by jspitz** [comment]
OK, so I am going to merge this PR as the last thing for 1.47. Agreed?

**Comment by reutenauer** [comment]
On Mon, Jan 20, 2020 at 01:42:06AM -0800, Jürgen Spitzmüller wrote:
> OK, so I am going to merge this PR as the last thing for 1.47. Agreed?

  Go for it :-)

**Comment by jspitz** [comment]
Done. Now 1.47 is ready to roll :-)

**Pull request merged**
