### PR TITLE
Changing \Authands for package authblk

### PR DESCRIPTION
**Pull request by niruvt**

### CODE REVIEW

**Comment by jspitz** [comment]
@reutenauer do we add definitions for such exotic captions (of specific packages)?

**Comment by NiranjanTambe** [comment]
I don't really know the policies of `polyglossia`, but why not? I mean if `polyglossia` provides translation for plain LaTeX commands, then why not for package-specific commands? What harm can it do?

**Comment by jspitz** [comment]
> I don't really know the policies of `polyglossia`

Me neither (policies concerning this question), that's why I am asking the person who knows.

**Comment by reutenauer** [comment]
As I said [on the XeTeX list](https://tug.org/pipermail/xetex/2020-April/027626.html), I think it makes sense to add this to Polyglossia in the absence of a more integrated policy.  But since the package `dramatist` is the one that prompted the discussion on the list, please do add translations for this package too before we merge the pull request.

**Comment by jspitz** [comment]
There are the [translator](https://www.ctan.org/pkg/translator) and [translations](https://www.ctan.org/pkg/translations) packages to ease i18n of packages (at least the latter supports both `babel` and `polyglossia`). But yes, there's nothing "standard".

**Comment by NiranjanTambe** [comment]
Hello @jspitz and @reutenauer!

Thanks for your response. Translations for package dramatist might take more time. Some of my friends are currently working on the same. I recently came across an error in `documentclass{beamer}` which was caused by a redefinition given by me. I have removed it from the master. Sorry for the wrong redefinition.

It would be better if we merge this pull-request soon, as the current file is causing error in `beamer` class.

**Comment by jspitz** [comment]
Can you please provide a separate request for the `\labelitemii` issue?

**Comment by jspitz** [comment]
For the record, the `\labelitemii` issue has been resolved at 9e197e5e70eff8

**Comment by jspitz** [comment]
Reconsidering this, I think this should be addressed in the `authblk` package itself which already provides (very) limited localization possibilities (with the `german` option).

**Pull request closed without merging**
