### PR TITLE
Use numerals command for formating number

### PR DESCRIPTION
**Pull request by bastien-roucaries**
This command will be used like arabic but typeset the number in the current locale

Could you please comment ?

I will like to add also a C locale that is the bare latex command.

### CODE REVIEW

**Comment by bastien-roucaries** [comment]
@josephwright @jspitz

**Comment by bastien-roucaries** [comment]
\documentclass{article}


\usepackage{polyglossia}
\newfontfamily\arabicfont[Script=Arabic]{scheherazade}

\setdefaultlanguage{german}
\setotherlanguage{english}
\setotherlanguage{arabic}

\begin{document}

\section{test}


\arabic{page}


\begin{Arabic}
  oooo \numerals{page} yyy \Numerals{6}
  \Numerals[]{(7+3)*2} xxx
\end{Arabic}
\end{document}

**Comment by jspitz** [comment]
I can't really comment on the code (I am not yet very familiar with expl3) but I like the idea.

**Comment by bastien-roucaries** [comment]
@jspitz about the name numerals ? Do you have a better idea ?

**Comment by jspitz** [comment]
Maybe `\localnumber`?

**Comment by bastien-roucaries** [comment]
Numerals is shorter

**Comment by wehro** [comment]
I did not check the code in detail, but it is against the expl3 coding convention to use @ signs within the names of commands or variables. One should use underscores instead.

**Comment by jspitz** [comment]
> Numerals is shorter

`\localnum`? `\locnum`?

**Comment by wehro** [comment]
I think `\localnumber` is fine. A speaking name is better than a short one.

**Comment by bastien-roucaries** [comment]
Corrected with your comments.

\renewcommand{\thesection}{\localnumber{section}} 

now work

**Pull request merged**
