### PR TITLE
korean: changed to nohyphenation and minor fixes

### PR DESCRIPTION
**Pull request by dohyunkim**
`hyphennames` has changed from `english` to `nohyphenation`; anyway, it turned out that `english` does not work anymore.
And some mimor fixes and adaptations to recent luatex engine.

### CODE REVIEW

**Comment by dohyunkim** [comment]
* it's not easy for me to catch the meaning of "correct the tex file".
* and nor of "external function". Do you mean "external file"?
* I'm afraid I do not have time to add detailed comments to the lua code for now. I will do that when I can make time.

On japanese/chinese: 
I did not considered japanese/chinese languages, as I do not have good enough knowledge about them.  It would be better to consult japanese/chinese guys for their own languages.

**Comment by bastien-roucaries** [comment]
I will rewrite.
Please slit the patch in a least three patch
1. First patch will only fixes the gloss file error not the lua error
2. second one will split the lua code out the gloss file to a korean.lua file
3. third one will make the change in the lua code
4. (optional) will comment the lua code

**Comment by dohyunkim** [comment]
Lua code has now been splitted out to a new file. 
File name is `polyglossia-korean.lua`, because `korean.lua` seems to be too generic.

**Comment by dohyunkim** [comment]
Thanks for merging.

In fact, `variant=classic` option in korean language seems to do the job somewhat approaching japanese typesetting. But it surely would be short of satisfaction in the eyes of native japanese users. As for chinese, beyond doubt we will have much more unsatifactory typesetting results.  

Anyway, though I have no ability to contribute generic code for CJK typesetting, it would be much appreciated if the code for korean language, especially the code regarding linebreak and spacing in `polyglossia-korean.lua`, can be a starting point for producing generic CJK module.

**Pull request merged**
